[{"source": "https://simonwillison.net", "title": "Finding and reporting an asyncio bug in Python 3.10", "description": "I found a bug in Python 3.10 today! Some notes on how I found it and my process for handling it once I figured out what was going on. Testing \u2026", "link": "https://simonwillison.net/2021/Oct/9/finding-and-reporting-a-bug/", "date_published": "2021-10-10 14:38:26.640024+00:00", "persistent": true, "user": "Thomas Pain", "language": "en-gb"}]